--------------------------------------------------------
--  DDL for Table ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "APP_SCHEMA"."ERROR_LOG" 
   (	"LOG_ID" NUMBER, 
	"CREATED_ON" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"ERRORCODE" NUMBER(*,0), 
	"CALLSTACK" VARCHAR2(4000 BYTE), 
	"ERRORSTACK" VARCHAR2(4000 BYTE), 
	"BACKTRACE" VARCHAR2(4000 BYTE), 
	"ERROR_INFO" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" ;
