--------------------------------------------------------
--  DDL for Table LEADS
--------------------------------------------------------

  CREATE TABLE "APP_SCHEMA"."LEADS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 CHAR), 
	"STAGE" VARCHAR2(50 CHAR), 
	"TAXID" NUMBER(14,0), 
	"INDUSTRY" VARCHAR2(30 BYTE), 
	"SOURCE" VARCHAR2(60 BYTE), 
	"PHONE" NUMBER, 
	"ADDRESS_STREET" VARCHAR2(200 BYTE), 
	"ADDRESS_ZIPCODE" NUMBER, 
	"ADDRESS_NUMBER" NUMBER, 
	"ADDRESS_COMPLEMENT" VARCHAR2(200 BYTE), 
	"ADDRESS_DISTRICT" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"SALES_REP" NUMBER, 
	"TAX_REGISTRATION" VARCHAR2(20 BYTE), 
	"CLIENT_CODE" NUMBER, 
	"BUDGET_VALUE" NUMBER, 
	"ORDER_VALUE" NUMBER, 
	"FINANCIAL_ANALYSIS" VARCHAR2(200 BYTE), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "APP_SCHEMA"."TRG_CRM_UPDATE_ERP" 
BEFORE INSERT OR UPDATE ON app_schema.leads
FOR EACH ROW
DECLARE
BEGIN
-- Call client update procedure
    PRC_UPDATE_CLIENTS(
        P_TAXID => lpad(:NEW.taxid,14,0),
        P_ID_CRM => :NEW.ID,
        P_COMPANY_NAME => :NEW.NAME,
        P_INDUSTRY => :NEW.INDUSTRY,
        P_TAX_REGISTRATION => :NEW.TAX_REGISTRATION,
        P_ADDRESS_STREET => :NEW.ADDRESS_STREET,
        P_ADDRESS_NUMBER => :NEW.ADDRESS_NUMBER,
        P_ADDRESS_COMPLEMENT => :NEW.ADDRESS_COMPLEMENT,
        P_ADDRESS_DISTRICT => :NEW.ADDRESS_DISTRICT,
        P_ADDRESS_ZIPCODE => :NEW.ADDRESS_ZIPCODE,
        P_CITY => :NEW.CITY,
        P_STATE => :NEW.STATE,
        P_PHONE => :NEW.PHONE,
        P_SALES_REP => :NEW.SALES_REP,
        P_INITIAL_LOAD => 'N',
        P_FINANCIAL_ANALYSIS => :NEW.FINANCIAL_ANALYSIS
    );

EXCEPTION
    WHEN OTHERS THEN
            pkg_error_mgr.log_error (
            'ERROR - INSERT_LEAD -> ' ||
            'TAXID: ' || :NEW.taxid ||
            ' - ID: ' || :NEW.ID ||
            ' - Name: ' || :NEW.NAME ||
            ' - Industry: ' || :NEW.INDUSTRY ||
            ' - Tax Registration: ' || :NEW.TAX_REGISTRATION ||
            ' - Address Street: ' || :NEW.ADDRESS_STREET ||
            ' - Address Number: ' || :NEW.ADDRESS_NUMBER ||
            ' - Address Complement: ' || :NEW.ADDRESS_COMPLEMENT ||
            ' - Address District: ' || :NEW.ADDRESS_DISTRICT ||
            ' - Address Zipcode: ' || :NEW.ADDRESS_ZIPCODE ||
            ' - City: ' || :NEW.CITY ||
            ' - State: ' || :NEW.STATE ||
            ' - Phone: ' || :NEW.PHONE ||
            ' - Sales Rep: ' || :NEW.SALES_REP ||
            ' - Financial Analysis: ' || :NEW.FINANCIAL_ANALYSIS ||
            ' - ERROR: ' || SQLERRM || 
            ' (Code: ' || SQLCODE || ')'
            );  
            raise_application_error(-20020, 'ERROR, '||SQLCODE||' - '||sqlerrm);
            
END;
/
ALTER TRIGGER "APP_SCHEMA"."TRG_CRM_UPDATE_ERP" ENABLE;
