--------------------------------------------------------
--  File created - Friday-October-11-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTACTS
--------------------------------------------------------

  CREATE TABLE "APP_SCHEMA"."CONTACTS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(60 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"PHONE" NUMBER, 
	"JOB_TITLE" VARCHAR2(30 BYTE), 
	"CLIENT_CODE" VARCHAR2(20 BYTE), 
	"IS_PRIMARY" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" ;
--------------------------------------------------------
--  DDL for Index CONTACTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_SCHEMA"."CONTACTS_PK" ON "APP_SCHEMA"."CONTACTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA" ;
--------------------------------------------------------
--  DDL for Trigger TRG_CRM_UPDATE_CONTACT_ERP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APP_SCHEMA"."TRG_CRM_UPDATE_CONTACT_ERP" AFTER
    INSERT OR UPDATE ON app_schema.contacts
    FOR EACH ROW
BEGIN
    PRC_UPDATE_CLIENT_CONTACTS(
         P_CLIENT => :NEW.CLIENT_CODE,
         P_NAME => :NEW.NAME,
         P_EMAIL => :NEW.EMAIL,
         P_PHONE => :NEW.PHONE,
         P_JOB_TITLE => :NEW.JOB_TITLE,
         P_IS_PRIMARY => :NEW.IS_PRIMARY,
         P_ID_CRM => :NEW.ID,
         P_OPERATION => CASE WHEN INSERTING THEN 'A'
    WHEN updating THEN
        'A'
    WHEN deleting THEN
        'D'
END
    );
END;
/
ALTER TRIGGER "APP_SCHEMA"."TRG_CRM_UPDATE_CONTACT_ERP" ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACTS
--------------------------------------------------------

  ALTER TABLE "APP_SCHEMA"."CONTACTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_SCHEMA"."CONTACTS" ADD CONSTRAINT "CONTACTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APP_DATA"  ENABLE;
