--------------------------------------------------------
--  File created - Friday-October-11-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VW_CRM_CLIENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APP_SCHEMA"."VW_CRM_CLIENTS" ("ID", "CLIENT_CODE", "BRANCH_CODE", "COMPANY_NAME", "TAXID", "SALES_REP", "COUNTRY", "STATE", "CITY", "CITY_CODE", "ADDRESS_ZIPCODE", "ADDRESS_STREET", "ADDRESS_NUMBER", "ADDRESS_DISTRICT", "ADDRESS_COMPLEMENT", "EMAIL", "TAX_REGISTRATION", "PHONE", "ID_CRM", "INTEGRATE_CRM", "INDUSTRY", "FINANCIAL_ANALYSIS", "BUDGET_VALUE", "HAS_ORDER", "ORDER_VALUE", "HAS_RETENTION", "SALES_REP_EMAIL") AS 
  select B.CLIENT || '-' || B.CODE ID
      ,B.CLIENT CLIENT_CODE
      ,B.CODE BRANCH_CODE
      ,B.DESCRIPTION COMPANY_NAME
      ,B.TAXID TAXID
      ,B.SALES_REP
      ,UTIL_PKG.INITCAP2(INITCAP(P.NAME)) COUNTRY
      ,DECODE(P.CODE, 'US', UTIL_PKG.INITCAP2(INITCAP(S.NAME)), null) STATE
      ,UTIL_PKG.INITCAP2(INITCAP(CT.CITY_NAME)) CITY
      ,CT.CITY_CODE CITY_CODE
      ,B.ZIPCODE ADDRESS_ZIPCODE
      ,B.ADDRESS ADDRESS_STREET
      ,B.NUMBER ADDRESS_NUMBER
      ,B.DISTRICT ADDRESS_DISTRICT
      ,B.COMPLEMENT ADDRESS_COMPLEMENT
      ,B.EMAIL EMAIL
      ,B.TAX_REGISTRATION TAX_REGISTRATION
      ,B.PHONE
      ,B.ID_CRM ID_CRM
      ,NVL(B.INTEGRATE_CRM,'N') INTEGRATE_CRM
      ,(select min(UTIL_PKG.INITCAP2(INITCAP(m.DESCRIPTION)))
          from CLIENT_INDUSTRIES Ic
              ,ERP_SCHEMA.INDUSTRIES m
         where Ic.CLIENT = B.CLIENT
           and Ic.BRANCH = B.CODE
           and Ic.INDUSTRY = m.INDUSTRY) INDUSTRY
      ,(select max(H.OBSERVATIONS)
          from ERP_SCHEMA.CREDIT_LIMIT_HISTORY H
         where H.CLIENT_CODE = C.CLIENT_CODE
           and DATE = (select max(DATE)
                         from ERP_SCHEMA.CREDIT_LIMIT_HISTORY H1
                        where H1.CLIENT_CODE = C.CLIENT_CODE)) FINANCIAL_ANALYSIS
      ,APP_SCHEMA.PKG_CRM_CLIENT.GET_BUDGET_VALUE(B.CLIENT, B.CODE, sysdate) BUDGET_VALUE
      ,APP_SCHEMA.PKG_CRM_CLIENT.HAS_ORDER(B.CLIENT, B.CODE, sysdate) HAS_ORDER
      ,APP_SCHEMA.PKG_CRM_CLIENT.GET_ORDER_VALUE(B.CLIENT, B.CODE, sysdate) ORDER_VALUE
      ,APP_SCHEMA.PKG_CRM_CLIENT.HAS_ORDER(B.CLIENT, B.CODE, sysdate + 30) HAS_RETENTION
      ,(select r.EMAIL from SALES_REPS r where r.CODE = B.SALES_REP) SALES_REP_EMAIL
  from CLIENTS C
      ,BRANCHES B
      ,CITIES CT
      ,COUNTRIES P
      ,STATES S
 where C.CLIENT_CODE = B.CLIENT
   and CT.ID = B.CITY
   and P.CODE = CT.COUNTRY_CODE
   and CT.STATE_CODE = S.CODE
;
